### ISSUE TITLE
FilestackClient->upload doesn't return neither Filestack\Filelink nor file content

### ISSUE THREAD

**Issue by lukepolak** [filestack/filestack-php#29]
It runs same value as UploadProcessor->run (because it calls it and returns it's return value immediately), which is array with fields 'status' and 'json'. It seems PHPDoc is wrong, and so are examples in readme.

**Comment by hueyl77** [comment]
hi Luke!  Thanks for bringing this to our attention.  Release https://github.com/filestack/filestack-php/tree/1.1.10 updated the code to return a Filelink object as it should.  Sorry if this caused you any frustrations.
